# Generated by Django 5.1.7 on 2025-03-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitem_menu_item_order_order_time"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.URLField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("appetizer", "Appetizer"),
                            ("main_course", "Main Course"),
                            ("dessert", "Dessert"),
                            ("beverage", "Beverage"),
                            ("side_dish", "Side Dish"),
                            ("breakfast", "Breakfast"),
                            ("special", "Chef Special"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="is_active",
        ),
        migrations.AddField(
            model_name="courier",
            name="busy_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courier",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="couriers",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
