# Generated by Django 5.1.7 on 2025-03-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0002_fooditem_delete_menuitem_remove_courier_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courier",
                to="restaurants.restaurant",
            ),
        ),
    ]
