# Generated by Django 5.1.7 on 2025-03-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitem_menu_item_order_order_time"),
        (
            "restaurants",
            "0002_fooditem_delete_menuitem_remove_courier_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="food_item",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.fooditem",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PREPARING", "Preparing"),
                    ("DELIVERING", "Delivering"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
