# Generated by Django 5.1.7 on 2025-03-14 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_food_item_alter_order_status"),
        (
            "restaurants",
            "0002_fooditem_delete_menuitem_remove_courier_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="restaurants.restaurant",
            ),
        ),
    ]
