# Generated by Django 5.1.7 on 2025-03-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_latitude",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_longitude",
        ),
    ]
